export const fields = {
  image: {
    name: "image",
    type: "file",
    id: "image",
  },
  name: {
    name: "name",
    placeholder: "Cтіл",
    label: "Назва",
    type: "text",
    id: "name",
  },
  price: {
    name: "price",
    placeholder: "5000",
    label: "Ціна, грн",
    type: "number",
    id: "price",
  },
  category: {
    name: "category",
    placeholder: "Столи",
    label: "Категорія",
    type: "search",
    id: "category",
  },
  quantity: {
    name: "quantity",
    placeholder: "5",
    label: "Кількість",
    type: "number",
    id: "quantity",
  },
  material: {
    name: "material",
    placeholder: "Дуб",
    label: "Матеріал",
    type: "search",
    id: "material",
  },
  color: {
    name: "color",
    placeholder: "Чорний",
    label: "Колір",
    type: "search",
    id: "color",
  },
  weight: {
    name: "weight",
    placeholder: "25",
    label: "Вага, кг",
    type: "number",
    id: "weight",
  },
  height: {
    name: "heigth",
    placeholder: "90",
    label: "Висота, см",
    type: "number",
    id: "heigth",
  },
  length: {
    name: "length",
    placeholder: "140",
    label: "Довжина, см",
    type: "number",
    id: "length",
  },
  width: {
    name: "width",
    placeholder: "60",
    label: "Ширина, см",
    type: "number",
    id: "width",
  },
  warranty: {
    name: "warranty",
    placeholder: "14 днів",
    label: "Гарантія на",
    type: "number",
    id: "warranty",
  },
  description: {
    name: "description",
    placeholder: "Вставте опис товару",
    label: "Опис",
    type: "number",
    id: "description",
  },
};
